---
  - name: "show remote environment"
    shell: env
  - name: "test directory stat"
    become: true
    shell: ls -la; pwd
    
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0
  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: "copy backend binaries"
    become: true
    synchronize:
      src: /root/project/backend
      dest: /home/ubuntu/
      recursive: true

  # - name: "copy node_modules"
  #   become: true
  #   synchronize:
  #     src: /usr/local/lib/node_modules
  #     dest: /home/ubuntu/
  #     recursive: true

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
    command: |
          # cd /home/ubuntu/backend
          # tar xzvf backend.tar.gz
          # mv home/circleci/project/backend .
          # cd backend
          # npm install -g npm@latest
          # npm install -g webpack-dev-server
          npm install
          npm run build
          # npm run start
          pm2 start npm --name backend -- start
          # pm2 start -f ./main.js
          pm2 ls

   # args:
     # chdir: /home/ubuntu/dist
    environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
