---
  - name: "show remote environment"
    shell: env
  - name: "test directory stat"
    become: true
    shell: ls -la; pwd

  - name: "copy backend binaries"
    become: true
    synchronize:
      src: /home/backend.tar.gz
      dest: /home/ubuntu/backend.tar.gz
      recursive: true

  # - name: "copy node_modules"
  #   become: true
  #   synchronize:
  #     src: /usr/local/lib/node_modules
  #     dest: /home/ubuntu/
  #     recursive: true

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
    command: |
          cd /home/ubuntu/
          tar xzvf backend.tar.gz
          mv /home/circlci/project/backend .
          cd backend
          npm install
          npm run build
          pm2 start npm --name backend -- start

   # args:
     # chdir: /home/ubuntu/dist
    environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
